package longtaillib

// #cgo CFLAGS: -g -std=gnu99 -m64 -pthread -msse4.1 -maes -DLONGTAIL_ASSERTS
// //#include "longtail/lib/brotli/longtail_brotli.c"
// //#include "longtail/lib/brotli/ext/common/dictionary.c"
// //#include "longtail/lib/brotli/ext/common/transform.c"
// //#include "longtail/lib/brotli/ext/dec/decode.c"
// //#include "longtail/lib/brotli/ext/dec/huffman.c"
// //#include "longtail/lib/brotli/ext/dec/state.c"
// //#include "longtail/lib/brotli/ext/enc/backward_references_hq.c"
// //#include "longtail/lib/brotli/ext/enc/backward_references.c"
// //#include "longtail/lib/brotli/ext/enc/bit_cost.c"
// //#include "longtail/lib/brotli/ext/enc/block_splitter.c"
// //#include "longtail/lib/brotli/ext/enc/brotli_bit_stream.c"
// //#include "longtail/lib/brotli/ext/enc/cluster.c"
// //#include "longtail/lib/brotli/ext/enc/compress_fragment_two_pass.c"
// //#include "longtail/lib/brotli/ext/enc/compress_fragment.c"
// //#include "longtail/lib/brotli/ext/enc/dictionary_hash.c"
// //#include "longtail/lib/brotli/ext/enc/encode.c"
// //#include "longtail/lib/brotli/ext/enc/encoder_dict.c"
// //#include "longtail/lib/brotli/ext/enc/entropy_encode.c"
// //#include "longtail/lib/brotli/ext/enc/histogram.c"
// //#include "longtail/lib/brotli/ext/enc/literal_cost.c"
// //#include "longtail/lib/brotli/ext/enc/memory.c"
// //#include "longtail/lib/brotli/ext/enc/metablock.c"
// //#include "longtail/lib/brotli/ext/enc/utf8_util.c"
// //#include "longtail/lib/brotli/ext/fuzz/decode_fuzzer.c"
import "C"
