name: Build Master

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Build & Test

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [amd64]
        include:
          - os: macos-latest
            arch: arm64

    runs-on: ${{matrix.os}}

    steps:
      - name: Set up Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Check out source code
        uses: actions/checkout@v4

      - name: test
        if: ${{ matrix.arch == 'amd64' }}
        run: |
          pushd ./longtaillib
          go test .
          popd
          pushd ./longtailstorelib
          go test .
          popd
          pushd ./commands
          go test .
          popd
          pushd ./remotestore
          go test .
          popd
        env:
          GOARCH: ${{matrix.arch}}
          CGO_ENABLED: 1

      - name: build cmd
        run: |
          pushd ./cmd/longtail
          go build .
          popd
        env:
          GOARCH: ${{matrix.arch}}
          CGO_ENABLED: 1
