name: Build Master

on:
  push:
    branches: [ main ]

jobs:
  linux:

    runs-on: ubuntu-latest
    env: 
      CGO_ENABLED: 0

    steps:
      - name: Set up Go 1.15.8
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.8

      - name: Check out source code
        uses: actions/checkout@v2

      - name: test
        run: |
          pushd ./longtaillib
          go test .
          popd
          pushd ./longtailstorelib
          go test .
          popd

      - name: build cmd
        run: |
          pushd ./cmd/longtail
          go build .
          popd

  macos:

    runs-on: macos-latest
    env: 
      CGO_ENABLED: 0

    steps:
      - name: Set up Go 1.15.8
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.8

      - name: Check out source code
        uses: actions/checkout@v2

      - name: test
        run: |
          pushd ./longtaillib
          go test .
          popd
          pushd ./longtailstorelib
          go test .
          popd

      - name: build cmd
        run: |
          pushd ./cmd/longtail
          go build .
          popd

  win32:

    runs-on: windows-latest
    env: 
      CGO_ENABLED: 0

    steps:
      - name: Set up Go 1.15.8
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.8

      - name: Check out source code
        uses: actions/checkout@v2

      - name: test
        run: |
          pushd ./longtaillib
          go test .
          popd
          pushd ./longtailstorelib
          go test .
          popd

      - name: build cmd
        run: |
          pushd ./cmd/longtail
          go build .
          popd
