name: Build Master

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Build & Test

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    runs-on: ${{matrix.os}}

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v2

      - name: test
        run: |
          pushd ./longtaillib
          go test .
          popd
          pushd ./longtailstorelib
          go test .
          popd
          pushd ./commands
          go test .
          popd
          pushd ./remotestore
          go test .
          popd

      - name: build cmd
        run: |
          pushd ./cmd/longtail
          go build .
          popd
